домашнее задание спринт 10
SvetlanaTimchenko/PlaylistMaker pull request #3
Opened 2023-04-02 20:18 UTC by SvetlanaTimchenko

2023-04-03 20:00 UTC, NoDopezzz requested changes

2023-04-03 20:00 UTC, kirillNay commented on app/src/main/java/com/timchenko/playlistmaker/TrackViewHolder.kt
> +        cover.contentDescription = item.artistName + " : " + item.trackName
👍 Отличная идея добавлять `contentDescription` в изображениям

2023-04-03 20:00 UTC, kirillNay commented on app/src/main/res/drawable/placeholderph.xml
> +      android:fillColor="#AEAFB4"/>
⏫ Цвета в векторных изображениях также можно выносить в файл ресурсов. Так, можно организовать более гибкую дизайн-систему приложения

2023-04-03 20:00 UTC, kirillNay commented on app/src/main/res/layout/track_item.xml
> +            android:ellipsize="end"
👍 Отличная идея обрабатывать кейс с длинным названием

2023-04-03 20:00 UTC, kirillNay commented on app/src/main/res/layout/track_item.xml
> +            android:id="@+id/description"
⚠️ Для description не выставлен шрифт текста. Согласно макетам он должен быть `@font/ys_display_regular`

2023-04-03 20:00 UTC, kirillNay commented on app/src/main/res/values-en/strings.xml
> +    <string name="track_name_placeholder">Track name</string>
⏫ Текст, который используется только для preview через `tools:text` не обязательно выносить в ресурсы

2023-04-03 20:22 UTC, SvetlanaTimchenko commented on app/src/main/res/layout/track_item.xml
> +            android:id="@+id/description"
замечание исправлено в коммите [324b267](https://github.com/SvetlanaTimchenko/PlaylistMaker/pull/3/commits/324b267c720119e68a1a88f8ebf4d75471ab06b7)

2023-04-03 20:27 UTC, SvetlanaTimchenko commented on app/src/main/res/values-en/strings.xml
> +    <string name="track_name_placeholder">Track name</string>
Я бы хотела уточнить здесь такой момент - локализацию. А если у нас несколько языков, тестеры из разных стран. Это не считается хорошим тоном сделать перевод?

2023-04-03 20:31 UTC, SvetlanaTimchenko commented on app/src/main/res/drawable/placeholderph.xml
> +      android:fillColor="#AEAFB4"/>
Спасибо, не знала, что так работает. Исправлено в коммите: [9547a22](https://github.com/SvetlanaTimchenko/PlaylistMaker/pull/3/commits/9547a2299724eb42a39f03d46d18c527966f03c2)

2023-04-03 20:50 UTC, NoDopezzz commented on app/src/main/res/values-en/strings.xml
> +    <string name="track_name_placeholder">Track name</string>
Так как в атрибуте `tools:text` прописывается текст только для `preview`, которая используется только разработчиками при верстке, о локализации можно сильно не задумываться. В `strings.xml` лучше выносить значения, которые непосредственно влияют на конечного пользователя. С ростом проекта файлы `strings.xml` будет увеличиваться, и чтобы в нем было проще ориентироваться, лучше не оставлять там "дебажные" данные

2023-04-03 20:50 UTC, NoDopezzz approved these changes

2023-04-04 11:43 UTC, SvetlanaTimchenko commented on app/src/main/res/values-en/strings.xml
> +    <string name="track_name_placeholder">Track name</string>
исправлено в коммите [e2db487](https://github.com/SvetlanaTimchenko/PlaylistMaker/pull/3/commits/e2db4876c4cf3310c25666ee2d78bb23eb03965f)

2023-04-04 11:43 UTC, merged